-- 사용자 생성
CREATE USER C##WEBDB IDENTIFIED BY webdb;

-- COOECT, RESOURCE 권한 부여
GRANT CONNECT, RESOURCE TO C##WEBDB;

-- 테이블 스페이스 생성(12이상)
ALTER USER C##WEBDB DEFAULT TABLESPACE users QUOTA unlimited ON users;
